// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("3965ef11-0e1a-479f-94a5-6cc57e1cae61"),
	low("f11dcd3f-f55e-4b42-8370-68142fdb5105"),
	medium("8ddebb5a-21ba-45cd-866f-f39592144f5a"),
	high("3434db7f-457c-421e-8c99-ebe1b7bcea9b"),
	custom("40c82158-d8d1-494a-9582-784f0772244b");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
