// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("66b6fd26-4597-42c3-b75e-6d2ea0a5b201"),
	Geocodio("2a7e8284-10e6-4ed9-b2a3-9d5deee4ddd1"),
	LocationIQ("a99df6e8-2ec9-4c83-841a-294916cf4e99"),
	MapQuest("c2f9b5d4-869d-47d3-819b-d521d9011cf3");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
