// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("2e6c0a11-7adb-4b39-9388-1f13725dec3c"),
	startsWith("5506ac69-6462-493f-9eee-f1cc6240d02f"),
	endsWith("c814e444-7df9-4bd3-90df-eeec3e16c0f7"),
	between("5fde4877-8de3-4cc6-af8f-a96a4b0f385c"),
	greater("01b86909-fa53-45ee-a5f1-61847c757f2a"),
	greaterEqual("aa5c2938-cc00-464e-a601-fc3b6cbb1dd8"),
	equal("29041bea-1781-41b4-9cfb-3f03ebd7c6e1"),
	notEqual("d2ec3f36-79f9-41a2-bab4-af7452d24bb4"),
	smaller("d77c7b3f-216b-483f-ba99-df39cf5e38fb"),
	smallerEqual("8012a6cd-3d24-430b-82ca-97ad99c24fab"),
	empty("7a92e212-df1a-4ebc-b8fc-4704ae02699b"),
	notEmpty("326bf772-ba19-4e11-89c2-cfee11ec63a2");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
