// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("c748b3f5-6d13-45bf-a105-a37e5b164700"),
	startsWith("9adaabb0-cecc-4cda-92cd-104f1d7179de"),
	endsWith("013e8f46-d598-4d18-96cd-0a7addaa9888"),
	between("8974183d-c30d-436e-af56-ddeb53fa4203"),
	greater("169343ca-f175-47fd-89c1-f57ef61d1bf1"),
	greaterEqual("b639638b-8141-4c21-9e1e-1846c331bbd4"),
	equal("434c4d95-df0b-4415-a73b-61541eb0295a"),
	notEqual("69eab61c-c702-4a0e-8700-a66b43bdd59c"),
	smaller("92fa7095-6846-4dcb-9ba0-6a67130d8bfe"),
	smallerEqual("c5593669-72fd-4f05-b57d-089d75917320"),
	empty("8de3ff6b-568e-47dd-8731-ba9cd3111b10"),
	notEmpty("efeec596-b7b0-47d9-a5cd-aaed6b95ab82");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
